name: Check documentation build

on:
  push:
    branches: [master, 'release*']
    tags: ['*']
  pull_request:
    paths:
    - 'docs/**'
    - 'mypyc/doc/**'
    - '**/*.rst'
    - '**/*.md'
    - CREDITS
    - LICENSE

jobs:
  require:
    uses: ./.github/workflows/require.yml
  docs:
    runs-on: ubuntu-latest
    needs: require
    env:
      TOXENV: docs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ needs.require.outputs.basepython }}
      - name: Install tox
        run: pip install --upgrade ${{ needs.require.outputs.setuptools }} ${{ needs.require.outputs.virtualenv }} ${{ needs.require.outputs.tox }}
      - name: Setup tox environment
        run: tox -e ${{ env.TOXENV }} --notest --no-provision
      - name: Test
        run: tox -e ${{ env.TOXENV }} --skip-pkg-install --skip-missing-interpreters false
